### ISSUE TITLE
Implement player controls

### ISSUE THREAD

**Issue by AdityaHarvi** [ECE493G14Capstone/Capstone#21]
Move Left:
Create a key-binding allowing players to press "A" to move their tetromino one tile to the left

Move Down:
Create a key-binding allowing players to press "S" to move their tetromino one tile down

Move Right:
Create a key-binding allowing players to press "D" to move their tetromino one tile to the right

Rotate CCW:
Create a key-binding allowing players to press "Q" to rotate their tetromino 90 degrees counterclockwise

Rotate CW:
Create a key-binding allowing players to press "E" to rotate their tetromino 90 degrees clockwise

**Comment by c25vdw** [comment]
closed by #89
